# Generated by Django 4.0.5 on 2022-06-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(max_length=32, unique=True, verbose_name='номер заказа')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='стоимость $')),
                ('cost_rub', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='стоимость руб.')),
                ('delivery_date', models.DateField(verbose_name='срок поставки')),
            ],
        ),
    ]
