# Generated by Django 4.0.5 on 2022-06-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='order_number',
            field=models.IntegerField(unique=True, verbose_name='номер заказа'),
        ),
    ]
