# Generated by Django 4.0.5 on 2022-06-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googledata', '0002_alter_numbers_order_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Numbers',
            new_name='NumbersModel',
        ),
        migrations.RenameField(
            model_name='numbersmodel',
            old_name='order_number',
            new_name='order',
        ),
    ]
